//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u21608611_HW3.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;

    public partial class authors
    {
        [Key]
        public int authorId { get; set; }

        [Display(Name = "Author Name")]
        [Required(ErrorMessage = "Author name is required")]
        [StringLength(50, ErrorMessage = "Author name cannot exceed 50 characters")]
        public string name { get; set; }

        [Display(Name = "Author Surname")]
        [Required(ErrorMessage = "Author surname is required")]
        [StringLength(50, ErrorMessage = "Author surname cannot exceed 50 characters")]
        public string surname { get; set; }

        [Display(Name = "Books")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<books> books { get; set; }
    }
}
