//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u21608611_HW3.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;

    public partial class borrows
    {
        [Key]
        public int borrowId { get; set; }

        [Display(Name = "Student ID")]
        [Required(ErrorMessage = "Student ID is required")]
        public Nullable<int> studentId { get; set; }

        [Display(Name = "Book ID")]
        [Required(ErrorMessage = "Book ID is required")]
        public Nullable<int> bookId { get; set; }

        [Display(Name = "Taken Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> takenDate { get; set; }

        [Display(Name = "Brought Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> broughtDate { get; set; }

        // You may want to add more data annotations here based on your requirements.

        public virtual books books { get; set; }
        public virtual students students { get; set; }
    }
}

