//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u21608611_HW3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class students
    {
        [Key]
        public int studentId { get; set; }

        [Display(Name = "Student Name")]
        [Required(ErrorMessage = "Student name is required")]
        [StringLength(100, ErrorMessage = "Student name cannot exceed 100 characters")]
        public string name { get; set; }

        [Display(Name = "Student Surname")]
        [Required(ErrorMessage = "Student surname is required")]
        [StringLength(100, ErrorMessage = "Student surname cannot exceed 100 characters")]
        public string surname { get; set; }

        [Display(Name = "Birthdate")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> birthdate { get; set; }

        [Display(Name = "Gender")]
        [StringLength(10, ErrorMessage = "Gender cannot exceed 10 characters")]
        public string gender { get; set; }

        [Display(Name = "Class")]
        [StringLength(10, ErrorMessage = "Class cannot exceed 10 characters")]
        public string @class { get; set; }

        [Display(Name = "Points")]
        [Range(0, int.MaxValue, ErrorMessage = "Points must be non-negative")]
        public Nullable<int> point { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrows> borrows { get; set; }
    }
}
