//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u21608611_HW3.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;

    public partial class types
    {
        [Key]
        public int typeId { get; set; }

        [Display(Name = "Type Name")]
        [Required(ErrorMessage = "Type name is required")]
        [StringLength(50, ErrorMessage = "Type name cannot exceed 50 characters")]
        public string name { get; set; }

        [Display(Name = "Books")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<books> books { get; set; }
    }
}
